### ISSUE TITLE
Can't install this on Manjaro KDE.

### ISSUE THREAD

**Issue by redbrain** [Marcel1202/HTMLWallpaper#8]
I'm using Manjaro KDE 20.03. In your [KDE Store](https://store.kde.org/p/1324580/) page, you have instructions for installing it via the plasma GUI.  Attempting to open wallpaper settings just results in a strange empty box:
![image](https://user-images.githubusercontent.com/42494361/85882248-73abb400-b7ce-11ea-85b5-49ea632d8dca.png)
 You also have manual install instructions. On moving it (using sudo mv), it just returns that "~/.local/share/plasma" doesn't exist. "usr/share/plasma" does, but after extracting it there it doesn't show up on next login. Your help would be appreciated.

**Comment by Marcel1202** [comment]
You can create directories using the mkdir command. If a directory doesn't exist ("~/.local/share/plasma" in your case), you can just create it yourself. Also, you don't have to use sudo since you are moving it inside your user folder. I don't how much point there is in installing this plugin though, as you have to configure it using the wallpaper settings dialog.

**Comment by redbrain** [comment]
Oh this issue is still open. Turned out I just needed a reboot and then it was fine!
